export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const FETCH_GAMES = "FETCH_GAMES";
export const SELECT_DATE = "SELECT_DATE";
export const FETCH_ROSTERS = "FETCH_ROSTERS";
export const CREATE_GUESS = "CREATE_GUESS";
export const CREATE_USER_COLLECTIONS = "CREATE_USER_COLLECTIONS";
export const FETCH_USER_GUESSES_BY_DATE = "FETCH_USER_GUESSES_BY_DATE";
